from pathlib import Path
import shutil, sys

p = Path('frontend/src/pages/Livros.jsx')
if not p.exists():
    sys.exit('Rode este script na raiz do projeto: frontend/src/pages/Livros.jsx não encontrado.')
text = p.read_text(encoding='utf-8')
shutil.copy2(p, p.with_suffix('.jsx.bak'))

def r(old,new,name):
    global text
    if old not in text:
        sys.exit(f'Trecho não encontrado: {name}. O arquivo mudou; restaure o backup e me avise.')
    text = text.replace(old,new,1)

r("""    const [authors, categories, publishers] = await Promise.all([\n      apiRequest('/api/livros/autores?page=1&page_size=100'),\n      apiRequest('/api/livros/categorias?page=1&page_size=100'),\n      apiRequest('/api/livros/editoras?page=1&page_size=100'),\n      apiRequest('/api/estoque/prateleiras'),\n      apiRequest('/api/estoque/secoes'),\n    ])\n    setAutores(authors)\n    setCategorias(categories)\n    setEditoras(publishers)\n    setPrateleiras(prateleiras)\n    setSecoes(secoes)\n""", """    const [authors, categories, publishers, shelves, sections] = await Promise.all([\n      apiRequest('/api/livros/autores?page=1&page_size=100'),\n      apiRequest('/api/livros/categorias?page=1&page_size=100'),\n      apiRequest('/api/livros/editoras?page=1&page_size=100'),\n      apiRequest('/api/estoque/prateleiras'),\n      apiRequest('/api/estoque/secoes'),\n    ])\n    setAutores(authors)\n    setCategorias(categories)\n    setEditoras(publishers)\n    setPrateleiras(shelves)\n    setSecoes(sections)\n""", 'loadReferences')

r("""  const [cameraOpen, setCameraOpen] = useState(false)\n  const [prateleiras, setPrateleiras] = useState([])\n  const [secoes, setSecoes] = useState([])\n""", """  const [cameraOpen, setCameraOpen] = useState(false)\n  const [prateleiras, setPrateleiras] = useState([])\n  const [secoes, setSecoes] = useState([])\n  const [quickMode, setQuickMode] = useState(false)\n  const [quickCount, setQuickCount] = useState(0)\n  const [lastQuickBook, setLastQuickBook] = useState(null)\n  const numeroRegistroRef = useRef(null)\n""", 'estados')

r("""  function startCreate() {\n    setEditing(null)\n""", """  function startCreate() {\n    setQuickMode(false)\n    setEditing(null)\n""", 'startCreate')

r("""  async function searchISBN(event, scannedValue = null) {\n""", """  function startQuickCreate() {\n    setQuickMode(true)\n    setQuickCount(0)\n    setLastQuickBook(null)\n    setEditing(null)\n    setDetails(null)\n    setForm({ ...emptyForm, numero_exemplares: '1' })\n    setIsbnSearch('')\n    setIsbnFeedback('')\n    setIsbnCover('')\n    setFeedback('')\n    setError('')\n    setFormOpen(true)\n    setTimeout(() => setCameraOpen(true), 150)\n  }\n\n  async function searchISBN(event, scannedValue = null) {\n""", 'startQuickCreate')

r("""      setIsbnCover(result.capa_url || '')\n      setIsbnFeedback(found ? 'Livro encontrado pelo ISBN.' : 'Não encontramos informações para este ISBN. Você pode continuar o cadastro manualmente.')\n""", """      setIsbnCover(result.capa_url || '')\n      setIsbnFeedback(found ? 'Livro encontrado pelo ISBN.' : 'Não encontramos informações para este ISBN. Você pode continuar o cadastro manualmente.')\n      if (quickMode) setTimeout(() => numeroRegistroRef.current?.focus(), 100)\n""", 'foco registro')

r("""  function startEdit(book) {\n    setEditing(book)\n""", """  function startEdit(book) {\n    setQuickMode(false)\n    setEditing(book)\n""", 'startEdit')

r("""      if (editing) await apiRequest(`/api/livros/${editing.id}`, { method: 'PUT', body: JSON.stringify(payload) })\n      else await apiRequest('/api/livros', { method: 'POST', body: JSON.stringify(payload) })\n      setFormOpen(false)\n      setFeedback(editing ? 'Livro atualizado com sucesso.' : 'Livro cadastrado com sucesso.')\n      await loadLivros()\n""", """      if (editing) await apiRequest(`/api/livros/${editing.id}`, { method: 'PUT', body: JSON.stringify(payload) })\n      else await apiRequest('/api/livros', { method: 'POST', body: JSON.stringify(payload) })\n\n      if (quickMode && !editing) {\n        const savedLocation = { prateleira_id: form.prateleira_id, secao_id: form.secao_id }\n        setQuickCount((current) => current + 1)\n        setLastQuickBook({ titulo: form.titulo, numero_registro: form.numero_registro })\n        setForm({ ...emptyForm, ...savedLocation, numero_exemplares: '1' })\n        setIsbnSearch('')\n        setIsbnFeedback('')\n        setIsbnCover('')\n        setFeedback('Livro cadastrado. Pronto para o próximo.')\n        await loadLivros()\n        setTimeout(() => setCameraOpen(true), 150)\n      } else {\n        setFormOpen(false)\n        setFeedback(editing ? 'Livro atualizado com sucesso.' : 'Livro cadastrado com sucesso.')\n        await loadLivros()\n      }\n""", 'salvar contínuo')

r("""      {formOpen && <LocationFields form={form} updateField={updateField} prateleiras={prateleiras} secoes={secoes} />}\n      <div className=\"module-toolbar\"><div><p className=\"eyebrow\">Catálogo</p><h1>Livros</h1><p className=\"page-description\">Consulta e manutenção das obras cadastradas na biblioteca.</p></div><button className=\"primary-button\" onClick={startCreate}><Plus size={16} /> Novo livro</button></div>\n""", """      {formOpen && !quickMode && <LocationFields form={form} updateField={updateField} prateleiras={prateleiras} secoes={secoes} />}\n      <div className=\"module-toolbar\"><div><p className=\"eyebrow\">Catálogo</p><h1>Livros</h1><p className=\"page-description\">Consulta e manutenção das obras cadastradas na biblioteca.</p></div><div className=\"modal-actions\"><button className=\"secondary-button\" onClick={startQuickCreate}>Cadastro rápido</button><button className=\"primary-button\" onClick={startCreate}><Plus size={16} /> Novo livro</button></div></div>\n""", 'toolbar')

r("""<h2 id=\"book-form-title\">{editing ? 'Editar livro' : 'Registrar novo livro'}</h2>""", """<h2 id=\"book-form-title\">{editing ? 'Editar livro' : quickMode ? 'Cadastro rápido de livros' : 'Registrar novo livro'}</h2>""", 'título')

r("""<form className=\"student-form catalog-form\" onSubmit={saveBook}><section className=\"catalog-section\"><h3>Classificação</h3>""", """<form className=\"student-form catalog-form\" onSubmit={saveBook}>{quickMode && <><section className=\"catalog-section\"><h3>Leitura do próximo livro</h3><p className=\"page-description\">Escaneie o ISBN e depois informe manualmente o Nº de Registro.</p><div className=\"isbn-search-row\"><input value={isbnSearch} onChange={(event) => setIsbnSearch(event.target.value)} placeholder=\"ISBN / código de barras\" /><button type=\"button\" className=\"secondary-button\" onClick={(event) => searchISBN(event)} disabled={isbnLoading}>{isbnLoading ? 'Buscando...' : 'Buscar ISBN'}</button><button type=\"button\" className=\"secondary-button camera-button\" onClick={() => setCameraOpen(true)} disabled={isbnLoading}>Escanear câmera</button></div>{isbnFeedback && <p className={`isbn-status ${isbnFeedback.startsWith('Livro encontrado') ? 'isbn-success' : ''}`}>{isbnFeedback}</p>}<p><strong>Cadastrados nesta sessão:</strong> {quickCount}</p>{lastQuickBook && <p><strong>Último:</strong> {lastQuickBook.numero_registro || 'Sem registro'} — {lastQuickBook.titulo}</p>}</section><LocationFields form={form} updateField={updateField} prateleiras={prateleiras} secoes={secoes} /></>}<section className=\"catalog-section\"><h3>Classificação</h3>""", 'painel rápido')

r("""<label>Nº de Registro<input name=\"numero_registro\" value={form.numero_registro} onChange={updateField} /></label><label>Nº de Exemplares <span className=\"required\">*</span><input type=\"number\" name=\"numero_exemplares\" value={form.numero_exemplares} onChange={updateField} min=\"1\" step=\"1\" required /></label>""", """<label>Nº de Registro<input ref={numeroRegistroRef} name=\"numero_registro\" value={form.numero_registro} onChange={updateField} /></label><label>Nº de Exemplares <span className=\"required\">*</span><input type=\"number\" name=\"numero_exemplares\" value={form.numero_exemplares} onChange={updateField} min=\"1\" step=\"1\" required disabled={quickMode} /></label>""", 'registro')

r("""<button type=\"submit\" className=\"primary-button\" disabled={saving}>{saving ? 'Salvando...' : 'Salvar livro'}</button>""", """<button type=\"submit\" className=\"primary-button\" disabled={saving}>{saving ? 'Salvando...' : quickMode ? 'Salvar e próximo' : 'Salvar livro'}</button>""", 'botão salvar')

p.write_text(text, encoding='utf-8')
print('Cadastro rápido v1 aplicado com sucesso.')
print('Backup:', p.with_suffix('.jsx.bak'))
